LOAD DATA
INFILE regions.sql
APPEND INTO TABLE s2559258.REGIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    GEOM "MDSYS.SDO_GEOMETRY",
    MIN_TEMP,
    AVG_WIND,
    AVG_PRECIP
)
