LOAD DATA 
INFILE 'regions.sql'
TRUNCATE
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE s2559258.REGIONS
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS (
    REGION_ID INTEGER EXTERNAL,
    NAME CHAR,
    GEOM COLUMN OBJECT (
        SDO_GTYPE INTEGER EXTERNAL,
        SDO_ELEM_INFO VARRAY TERMINATED BY '|/' (elements FLOAT EXTERNAL),
        SDO_ORDINATES VARRAY TERMINATED BY '|/' (ordinates FLOAT EXTERNAL)
    ),
    MIN_TEMP FLOAT EXTERNAL,
    AVG_WIND FLOAT EXTERNAL,
    AVG_PRECIP FLOAT EXTERNAL
)
