LOAD DATA 
INFILE 'parking.sql'
TRUNCATE
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE s2559258.PARKING
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS (
    PARKING INTEGER EXTERNAL,
    NAME CHAR,
    AREA CHAR,
    GEOM COLUMN OBJECT (
        SDO_GTYPE INTEGER EXTERNAL,
        SDO_ELEM_INFO VARRAY TERMINATED BY '|/' (elements FLOAT EXTERNAL),
        SDO_ORDINATES VARRAY TERMINATED BY '|/' (ordinates FLOAT EXTERNAL)
    )
)
