LOAD DATA
INFILE 'pubs.sql'
APPEND
INTO TABLE s2559258.pubs
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY "'" TRAILING NULLCOLS
(
  PUB,
  NAME,
  XCOORD,
  YCOORD,
  RATING "CASE WHEN :RATING = 'NULL' THEN NULL ELSE :RATING END"
)
